apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: tony
  namespace: argocd
spec: 
  destination: 
    namespace: tony
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: application-sets
    repoURL: "https://github.com/superman566/play_argocd.git"
    targetRevision: main
  syncPolicy:
    automated: 
      automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true